#!/bin/sh
# postinst script for dsnote.

set -e

show_info() {
    echo "** Some features of Speech Note may require optional Python packages"
    echo "** Please check the help or project page for more info"
}

case "$1" in
    configure)
    show_info
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0

