/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../dbus/org.freedesktop.portal.GlobalShortcuts.xml -p dbus_portal_globalshortcuts_inf
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUS_PORTAL_GLOBALSHORTCUTS_INF_H
#define DBUS_PORTAL_GLOBALSHORTCUTS_INF_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.portal.GlobalShortcuts
 */
class OrgFreedesktopPortalGlobalShortcutsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.portal.GlobalShortcuts"; }

public:
    OrgFreedesktopPortalGlobalShortcutsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopPortalGlobalShortcutsInterface();

    Q_PROPERTY(uint version READ version)
    inline uint version() const
    { return qvariant_cast< uint >(property("version")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusObjectPath> BindShortcuts(const QDBusObjectPath &session_handle, const QList<QPair<QString,QVariantMap>> &shortcuts, const QString &parent_window, const QVariantMap &options)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(session_handle) << QVariant::fromValue(shortcuts) << QVariant::fromValue(parent_window) << QVariant::fromValue(options);
        return asyncCallWithArgumentList(QStringLiteral("BindShortcuts"), argumentList);
    }

    inline QDBusPendingReply<QDBusObjectPath> CreateSession(const QVariantMap &options)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(options);
        return asyncCallWithArgumentList(QStringLiteral("CreateSession"), argumentList);
    }

    inline QDBusPendingReply<QDBusObjectPath> ListShortcuts(const QDBusObjectPath &session_handle, const QVariantMap &options)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(session_handle) << QVariant::fromValue(options);
        return asyncCallWithArgumentList(QStringLiteral("ListShortcuts"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Activated(const QDBusObjectPath &session_handle, const QString &shortcut_id, qulonglong timestamp, const QVariantMap &options);
    void Deactivated(const QDBusObjectPath &session_handle, const QString &shortcut_id, qulonglong timestamp, const QVariantMap &options);
    void ShortcutsChanged(const QDBusObjectPath &session_handle, const QList<QPair<QString,QVariantMap>> &shortcuts);
};

namespace org {
  namespace freedesktop {
    namespace portal {
      typedef ::OrgFreedesktopPortalGlobalShortcutsInterface GlobalShortcuts;
    }
  }
}
#endif
