/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbus/org.mkiol.Stt.xml -p src/dbus_stt_inf
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus_stt_inf.h"

/*
 * Implementation of interface class OrgMkiolSttInterface
 */

OrgMkiolSttInterface::OrgMkiolSttInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgMkiolSttInterface::~OrgMkiolSttInterface()
{
}

