/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../dbus/org.freedesktop.Application.xml -p dbus_application_inf
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUS_APPLICATION_INF_H
#define DBUS_APPLICATION_INF_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.Application
 */
class OrgFreedesktopApplicationInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.Application"; }

public:
    OrgFreedesktopApplicationInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopApplicationInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Activate(const QVariantMap &platform_data)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(platform_data);
        return asyncCallWithArgumentList(QStringLiteral("Activate"), argumentList);
    }

    inline QDBusPendingReply<> ActivateAction(const QString &action_name, const QVariantList &parameter, const QVariantMap &platform_data)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(action_name) << QVariant::fromValue(parameter) << QVariant::fromValue(platform_data);
        return asyncCallWithArgumentList(QStringLiteral("ActivateAction"), argumentList);
    }

    inline QDBusPendingReply<> Open(const QStringList &uris, const QVariantMap &platform_data)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(uris) << QVariant::fromValue(platform_data);
        return asyncCallWithArgumentList(QStringLiteral("Open"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freedesktop {
    typedef ::OrgFreedesktopApplicationInterface Application;
  }
}
#endif
