/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ../dbus/org.kde.Klipper.xml -p dbus_klipper_inf
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUS_KLIPPER_INF_H_1762702122
#define DBUS_KLIPPER_INF_H_1762702122

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.kde.klipper.klipper
 */
class OrgKdeKlipperKlipperInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.klipper.klipper"; }

public:
    OrgKdeKlipperKlipperInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgKdeKlipperKlipperInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> getClipboardContents()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getClipboardContents"), argumentList);
    }

    inline QDBusPendingReply<> setClipboardContents(const QString &s)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(s);
        return asyncCallWithArgumentList(QLatin1String("setClipboardContents"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace kde {
    namespace klipper {
      typedef ::OrgKdeKlipperKlipperInterface klipper;
    }
  }
}
#endif
